# Generated by Django 3.1.4 on 2021-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210116_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_num',
            field=models.CharField(max_length=50, null=True, verbose_name='acc'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=50, null=True, verbose_name='bank'),
        ),
    ]
