# Generated by Django 3.1.4 on 2021-01-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210117_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acc_num',
            new_name='account_number',
        ),
    ]
