# Generated by Django 3.1.4 on 2021-01-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210117_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rider',
        ),
    ]
