# Generated by Django 3.1.4 on 2021-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='subaccount_id',
            field=models.CharField(default='fake', max_length=100, verbose_name='account_id'),
            preserve_default=False,
        ),
    ]
