# Generated by Django 3.1.4 on 2021-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rider_subaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='country',
            field=models.CharField(default='NG', max_length=255),
            preserve_default=False,
        ),
    ]
