# Generated by Django 3.1.4 on 2021-01-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('seller', '0003_auto_20210105_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='delivery.rider'),
        ),
    ]
