# Generated by Django 3.1.4 on 2021-01-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210119_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12, verbose_name='Shipping charge (inc. tax)'),
        ),
    ]
